### ISSUE TITLE
True black theme

### ISSUE THREAD

**Issue by Donkey-Doug** [davidtakac/prognoza#13]
Make it possible to select true black theme. Also make it possible to follow system settings and have true black theme.

**Comment by davidtakac** [comment]
Thank you for the suggestion and for taking an interest in the project, but I will not implement a true black theme because: 
- It would not be compatible with the mood feature (gray for cloudy, blue for rain, etc) that's based on current conditions. 
- It would compromise text legibility, see [Material Design guidelines](https://m2.material.io/design/color/dark-theme.html#properties) for more info.

**Comment by Korb** [comment]
Google doesn't stick to one standard dark color theme in its apps. In most cases it uses `121317`: Calendar, Contacts, Digital Wellbeing, Docs, Drive, GMail, Keep, Sheets, Slides, and Translate. But in some cases, Google uses `0d0d0d` (Home), `181c1f` (Phone) and `131313` (Play).

`0d0d0d` is close enough to `000` that I support the suggestion to use it when implementing a pure black background.
