### ISSUE TITLE
Make current temperature smaller

### ISSUE THREAD

**Issue by davidtakac** [davidtakac/prognoza#19]
Originally brought up in #17: 
> could you please make the temperature a bit smaller? half the size would be good, this would let the other informations much more space on the screen

**Comment by davidtakac** [comment]
The next update will have the current temperature reduced from 200 to 170 sp (commit 609ebff). I would love to hear more thoughts on this.

**Comment by muellerto** [comment]
I know, it's hard to imagine in Croatia :-) but the size must at least be small enough so that a temperature like `-27°C` will be displayed definitely on one line without a conflict. If you plan to let the user decide to have °F instead °C you get also three digit values (hundreds) in summer time.

**Comment by davidtakac** [comment]
> that a temperature like -27°C will be displayed definitely on one line without a conflict.

I see what you mean. The text size shrinks to put longer temps (like 120° or -25°) on a single line, so this shouldn't be a problem. 

> current temperature reduced from 200 to 170 sp

Upon further testing, I didn't like the way 170sp looked. It was like the temperature wanted to be big, but was too shy to make a statement :smile: I reduced it to 184sp for version 3.0.1. I think it looks better than 200sp, but it's still prominent and eye-catching.

**Comment by 0-5-0** [comment]
I mostly rely on the feels like temperature but 184sp looks fine on my phone for current temperature compared to the rest of the text in 3.0.1. I didn't see what 170 looks like but I understand what you're saying :)

**Comment by davidtakac** [comment]
Thanks for sharing your thoughts, I appreciate it :) I think I figured it out. I treated the current temperature like regular text and sizing it to 184sp is HUGE on some devices. I'm working on making it take up ~20% of the screen instead. This makes it consistent across devices.

**Comment by muellerto** [comment]
I do not understand your dither with the size of the temperature. Why must this number be so ridiculously big? Nobody, absolutely nobody, has an advantage from that. OK, I can read it from 5m distance, but do I have a 5m arm, or what?

(I made a screenshot and would have placed it here but upload doesn't work.)

As a developer you must always rethink your work from what the user needs. - The user has in the moment when he opens your app one main question: _how is it at the moment and how will it be in some hours?_ And the second part of that question is at least as important as the first part, probably it's even more important since I can see _how it is at the moment_ when I look out of the window. - What the user gets in the moment when he opens your app is a big number with a wrong unit (°) and an icon, not more, and this is answering only the first part of his question. For the second part he must scroll down.

But the solution would really be very easy: reduce the size of the temperature at least to the half, I would prefer to the third of its actual size, or spoken absolutely to about 12mm maximum, this is about 10% (or even only 7%) of the screen height. This makes it still the eye catcher but gives you the opportunity to place the current weather icon right of the temperature and makes a lot of space (half of the screen!) usable for at least three or four rows of weather forecast. Everything would be visible at the first glance.

**Comment by davidtakac** [comment]
I don't care if you understand and I don't "have" to do anything. This is a free app. If you don't like the design or think that I'm using "the wrong unit", just use something else.

**Comment by muellerto** [comment]
> I don't care if you understand and I don't "have" to do anything.

Yes, I'm the user, why should you care?

> This is a free app. If you don't like the design or think that I'm using "the wrong unit", just use something else.

You didn't understand until now that I'm on your side. I'm a developer myself, I know what I'm talking about. And I opened this case to help you to improve your software because it has the potential to become a good one. Especially it's not too complex until now.

OK. Uninstalled.

**Comment by 0-5-0** [comment]
> OK. Uninstalled.

You're not just arrogant, you're hilarious.

Thankfully David has made his software open source and free so anyone can fork it and design it how they see fit, that's mighty nice of David. I'm looking forward to seeing your fork.

**Comment by muellerto** [comment]
>>    OK. Uninstalled.
>
> You're not just arrogant, you're hilarious.

Another one who didn't understand.

I never said the app must now be like this and this and required immediate implementation until tomorrow. I said the app could be improved a lot by a much smaller temperature. That was the only intention of this case and that was honest and reasoned, and is it still. The discussion ended in "I don't care" and "use something else". Think about it. But without me now, I have a life.

**Comment by 0-5-0** [comment]
> Another one who didn't understand.
> 
Re-read what you wrote yesterday, you were condescending and arrogant, that's why the tone changed. Telling David how to be a DEV, telling the rest of us users how we should like our number sizes (what if I like reading it from 5m away). It's possible for others to have a point of view different than your own. As I said, you came across arrogant and condescending (intentionally or not).

**Comment by davidtakac** [comment]
Yeah, the tone is what I had issue with, not the feedback itself. It really **was** way too big on some devices. This was a bug and it’s fixed in 3.1.0.
